// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: avtorizate.proto

package avtorizate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение запроса для аутентификации
type AvtorizateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvtorizateRequest) Reset() {
	*x = AvtorizateRequest{}
	mi := &file_avtorizate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvtorizateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvtorizateRequest) ProtoMessage() {}

func (x *AvtorizateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avtorizate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvtorizateRequest.ProtoReflect.Descriptor instead.
func (*AvtorizateRequest) Descriptor() ([]byte, []int) {
	return file_avtorizate_proto_rawDescGZIP(), []int{0}
}

func (x *AvtorizateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ на запрос аутентификации
type AvtorizateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvtorizateResponse) Reset() {
	*x = AvtorizateResponse{}
	mi := &file_avtorizate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvtorizateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvtorizateResponse) ProtoMessage() {}

func (x *AvtorizateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avtorizate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvtorizateResponse.ProtoReflect.Descriptor instead.
func (*AvtorizateResponse) Descriptor() ([]byte, []int) {
	return file_avtorizate_proto_rawDescGZIP(), []int{1}
}

func (x *AvtorizateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AvtorizateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_avtorizate_proto protoreflect.FileDescriptor

const file_avtorizate_proto_rawDesc = "" +
	"\n" +
	"\x10avtorizate.proto\x12\fauth_service\")\n" +
	"\x11AvtorizateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"H\n" +
	"\x12AvtorizateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2c\n" +
	"\n" +
	"Avtorizate\x12U\n" +
	"\x10AvtorizateMethod\x12\x1f.auth_service.AvtorizateRequest\x1a .auth_service.AvtorizateResponseB\x11Z\x0fpkg/;avtorizateb\x06proto3"

var (
	file_avtorizate_proto_rawDescOnce sync.Once
	file_avtorizate_proto_rawDescData []byte
)

func file_avtorizate_proto_rawDescGZIP() []byte {
	file_avtorizate_proto_rawDescOnce.Do(func() {
		file_avtorizate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avtorizate_proto_rawDesc), len(file_avtorizate_proto_rawDesc)))
	})
	return file_avtorizate_proto_rawDescData
}

var file_avtorizate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_avtorizate_proto_goTypes = []any{
	(*AvtorizateRequest)(nil),  // 0: auth_service.AvtorizateRequest
	(*AvtorizateResponse)(nil), // 1: auth_service.AvtorizateResponse
}
var file_avtorizate_proto_depIdxs = []int32{
	0, // 0: auth_service.Avtorizate.AvtorizateMethod:input_type -> auth_service.AvtorizateRequest
	1, // 1: auth_service.Avtorizate.AvtorizateMethod:output_type -> auth_service.AvtorizateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avtorizate_proto_init() }
func file_avtorizate_proto_init() {
	if File_avtorizate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avtorizate_proto_rawDesc), len(file_avtorizate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avtorizate_proto_goTypes,
		DependencyIndexes: file_avtorizate_proto_depIdxs,
		MessageInfos:      file_avtorizate_proto_msgTypes,
	}.Build()
	File_avtorizate_proto = out.File
	file_avtorizate_proto_goTypes = nil
	file_avtorizate_proto_depIdxs = nil
}
