// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: avtorizate.proto

package avtorizate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Avtorizate_AvtorizateMethod_FullMethodName = "/auth_service.Avtorizate/AvtorizateMethod"
)

// AvtorizateClient is the client API for Avtorizate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvtorizateClient interface {
	// Метод аутентификации пользователя
	AvtorizateMethod(ctx context.Context, in *AvtorizateRequest, opts ...grpc.CallOption) (*AvtorizateResponse, error)
}

type avtorizateClient struct {
	cc grpc.ClientConnInterface
}

func NewAvtorizateClient(cc grpc.ClientConnInterface) AvtorizateClient {
	return &avtorizateClient{cc}
}

func (c *avtorizateClient) AvtorizateMethod(ctx context.Context, in *AvtorizateRequest, opts ...grpc.CallOption) (*AvtorizateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvtorizateResponse)
	err := c.cc.Invoke(ctx, Avtorizate_AvtorizateMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvtorizateServer is the server API for Avtorizate service.
// All implementations must embed UnimplementedAvtorizateServer
// for forward compatibility.
type AvtorizateServer interface {
	// Метод аутентификации пользователя
	AvtorizateMethod(context.Context, *AvtorizateRequest) (*AvtorizateResponse, error)
	mustEmbedUnimplementedAvtorizateServer()
}

// UnimplementedAvtorizateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvtorizateServer struct{}

func (UnimplementedAvtorizateServer) AvtorizateMethod(context.Context, *AvtorizateRequest) (*AvtorizateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvtorizateMethod not implemented")
}
func (UnimplementedAvtorizateServer) mustEmbedUnimplementedAvtorizateServer() {}
func (UnimplementedAvtorizateServer) testEmbeddedByValue()                    {}

// UnsafeAvtorizateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvtorizateServer will
// result in compilation errors.
type UnsafeAvtorizateServer interface {
	mustEmbedUnimplementedAvtorizateServer()
}

func RegisterAvtorizateServer(s grpc.ServiceRegistrar, srv AvtorizateServer) {
	// If the following call pancis, it indicates UnimplementedAvtorizateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Avtorizate_ServiceDesc, srv)
}

func _Avtorizate_AvtorizateMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvtorizateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvtorizateServer).AvtorizateMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avtorizate_AvtorizateMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvtorizateServer).AvtorizateMethod(ctx, req.(*AvtorizateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Avtorizate_ServiceDesc is the grpc.ServiceDesc for Avtorizate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Avtorizate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.Avtorizate",
	HandlerType: (*AvtorizateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvtorizateMethod",
			Handler:    _Avtorizate_AvtorizateMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avtorizate.proto",
}
